# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19bd54159d5fa480f05fd71992b846e5cc3fd6d90d44593ae2668a77fb8734b0378dd31285765bc5027c1e14e6539a369f7a596ca6a760aca4c1a48f4eef0138

test:
  secret_key_base: fdfb310991d111e18e0b2f92d444eab1ffe9d1799f79d4362a0b6b4a6d2699d8a969b16f3f6418d865494c769e112531e792bd788a445bf286bb2439d404aefd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
